# Generated by Django 4.2.2 on 2023-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_messages_alter_project_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
