# Generated by Django 4.2.2 on 2023-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_endorsements'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsements',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
