# Generated by Django 4.2.2 on 2023-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='ted-ed-logo-featured.jpg', null=True, upload_to=''),
        ),
    ]
