# Generated by Django 4.2.2 on 2023-06-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsements',
            name='approved',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
